### ISSUE TITLE
add prunner by default

### ISSUE THREAD

**Issue by greenify** [biojs/biojs-sniper#5]
I am super lazy, so I have written [`prunner`](https://www.npmjs.com/package/prunner) that allows one to run two commands 

```
prunner 'command 1' 'command 2'
```

I know that people probably would like to have, but I don't have a Windows machine to test `prunner`. So as if someone can assure that `prunner` works fine on Windows, I would be happy to add it to our slush program ;-)

```
prunner 'npm run sniper' 'npm run watch'
```

**Comment by greenify** [comment]
Oh this belongs to the slush.

`prunner` is tested on Windows and now included by default into slush.

**Comment by daviddao** [comment]
prunner kills slush-biojs command. Need sudo now. Doesn't work. I recommend to remove it

**Comment by greenify** [comment]
for reference the error was 

```
346 verbose stack Error: EACCES, unlink '/Users/David/node-tsnejs/node_modules/prunner/node_modules/.bin/win-spawn'
347 verbose cwd /Users/David/node-tsnejs
348 error Darwin 14.0.0
349 error argv "node" "/usr/local/bin/npm" "install"
350 error node v0.10.31
351 error npm  v2.5.0
352 error path /Users/David/node-tsnejs/node_modules/prunner/node_modules/.bin/win-spawn
353 error code EACCES
354 error errno 3
355 error Error: EACCES, unlink '/Users/David/node-tsnejs/node_modules/prunner/node_modules/.bin/win-spawn'
355 error  { [Error: EACCES, unlink '/Users/David/node-tsnejs/node_modules/prunner/node_modules/.bin/win-spawn']
355 error   errno: 3,
355 error   code: 'EACCES',
355 error   path: '/Users/David/node-tsnejs/node_modules/prunner/node_modules/.bin/win-spawn' }
356 error Please try running this command again as root/Administrator.
```

As I can't explain this - `win-spawn` [was removed](https://github.com/greenify/prunner/commit/aeb7dfceac8e69315980b9e8393af923ac16ac68) from prunner and added as static dependency ...
